### ISSUE TITLE
[feature request] Add information to weight

### ISSUE THREAD

**Issue by Aohzan** [joostlek/python-withings#140]
Hello,

Withings API seems to provide information about weight ([doc](https://developer.withings.com/api-reference/#tag/measure/operation/measure-getmeas) like: attrib, date, comment)
Is it possible to get those information, specially date, because I would like to trigger an alert if weight date taken is older than x days ?

Thank you for this and all your work :pray:

**Comment by joostlek** [comment]
You mean as sensor in home assistant?

**Comment by Aohzan** [comment]
Yes sorry, add those information here, to get added as attributes in the weight sensor in HA

**Comment by joostlek** [comment]
Hmm, the thing is that the latest date is something that is already handled by Home Assistant. So I don't think we can add them (as HA already knows the latest date).

Attribution might be useful, as is comment. But they are stored on measurement level, not on measurement type level

**Comment by joostlek** [comment]
Yep, but that's also the reason why we can't include it since those are guidelines

**Comment by Aohzan** [comment]
hello @joostlek , do we close this issue since it won't be done ?

**Comment by joostlek** [comment]
I'll close it indeed. Thanks for your suggestion 🙏
