### ISSUE TITLE
226 is an unsupported value for <enum 'MeasurementType'>

### ISSUE THREAD

**Issue by vitjurasek** [joostlek/python-withings#211]
In log of HA

Logger: aiowithings
Zdroj: components/withings/coordinator.py:102
První výskyt: 08:33:53 (28 výskyty)
Naposledy logováno: 13:03:53

226 is an unsupported value for <enum 'MeasurementType'>, please report this at https://github.com/joostlek/python-withings/issues

actual version of HA and integration

**Comment by joostlek** [comment]
Duplicate of #157
