### ISSUE TITLE
Receive 227 is an unsupported value for <enum 'MeasurementType'> in HA logs

### ISSUE THREAD

**Issue by sebeard** [joostlek/python-withings#434]
# Problem/Motivation

> Repeated error/warning logs appearing in Home Assistant. Raising here as recommended by logging message

## Expected behavior

> Measurement types to support enumerations

## Actual behavior

> Unrecognised measurement type 227 not in enumeration list

## Steps to reproduce

> Screenshot attached. Integrate with Home Assistant, enable all entities and restart Home Assistant - presumably require specific devices (I own a Body Comp, BPM Connect and Thermo)

## Proposed changes

> Add new enum to list assuming Withings have actually updated their documentation (I couldn't find it so guessing not). 

<img width="904" alt="Screenshot 2024-11-09 at 10 21 06" src="https://github.com/user-attachments/assets/e6d8a3fa-8171-4c78-a87b-2d1e70a2feb1">

**Comment by sebeard** [comment]
This appears near identical to issue #86 - measurement type 10 appears to be Systolic Blood Pressure (mmHg)

**Comment by joostlek** [comment]
What devices do you have and are there stats you can see in the withings app (or dashboard) that are unable to be viewed from HA?

**Comment by sebeard** [comment]
Thanks for the swift response @joostlek. I have 

- BPM Connect running Software Version 1501
- Body Comp running Software Version 1181
- Thermo running Software Version 1551

I'll have a look through the app shortly. I can only see in HA 2 things that have 'unknown' against them:

1. Withings Elevation change last workout
2. Withings Last workout intensity

**Comment by joostlek** [comment]
No I mean, apparently Withings has a new measurement type that we don't support yet. And since Withings isn't the best with documenting, I need you to find out what this value means, so we can also support it. So have a look at the withings web dashboard, there you can usually see a lot of raw data, and that might help you with this

![image](https://github.com/user-attachments/assets/6a578a4f-8820-4072-8cce-0a30a3c44a6b)

**Comment by sebeard** [comment]
I couldn't see anything obvious in the dashboard but I grabbed the raw json from a network trace to try and correlate.

First up; the device model in the response is 18 which doesn't currently map to anything in this library. It's a Withings Body Comp. It's this device that's sending back the 227 measurement type. There are a number of other measurement types that don't currently tie to anything in the docs or the library that are still 'unknown'. The device type at least gives us a slight hint along with the fact it comes back with the weight data rather than the nerve health, and heart related data (PWV/BPM)

Here's a list of missing units from the body comp device that I can see.
- 234 (measurement types sent back alongside Nerve Health Score)
- 177 (this and all following in the weight measurements)
- 178
- 189
- 201
- 202
- 203
- 207
- 227
- 122
- 93
- 94
- 95


Would it be helpful if I shared the JSON returned for this reading specifically?

**Comment by joostlek** [comment]
The API that you got data from here is different for the one we get data from, so the JSON is not that interesting, but I am interested if you can correlate the values of the numbers to what they mean, since that data probably is rendered on the dashboard somewhere (one would assume)

**Comment by sebeard** [comment]
Ok managed to download the raw data to correlate with the JSON outputs and I'm pretty sure it's the following as they tie up.

- 234 seems to correlate to Max Nerve Health Score Feet (167 being Nerve Health Score Conductance 2 Electrodes Feet)
- 177 correlates to Impedance 50kHz for segments 
- 178 correlates to Impedance 250kHz for segments 
- 189 correlates to Impedance 6.25kHz for segments 
- 201 could be either Phase 6.25kHz or 50kHz or 250kHz segment. Mine are all very slightly negative and round to 0. Based on list ordering which seems to correlate too I'd guess this is Phase 6.25kHz segment.
- 202 could be either Phase 6.25kHz or 50kHz or 250kHz segment. Mine are all very slightly negative and round to 0. Based on list ordering which seems to correlate too I'd guess this is Phase 50kHz segment
- 203 could be either Phase 6.25kHz or 50kHz or 250kHz segment. Mine are all very slightly negative and round to 0. Based on list ordering which seems to correlate too I'd guess this is Phase 250kHz segment
- 207 is BIA error
- 227 is Metabolic Age
- 122 is Fat Free %
- 93 is Muscle %
- 94 is Bone %
- 95 is Water %

**Comment by sebeard** [comment]
Metabolic age is just an estimated age measure e.g a value represents the average basal metabolic rate for someone of that age. That allows the UI to highlight is higher or lower than average compared to your actual age.
