### ISSUE TITLE
Cannot add Withings integration

### ISSUE THREAD

**Issue by bevanting** [joostlek/python-withings#435]
# Problem/Motivation

After clicking "Add Integration", I get a screen saying it needs to "visit an external website". It takes me to the Withings website and immediately I see "pick a user" screen. I select one and "allow this app" and I get the "redirect_uri_mismatch: etc" message.
After searching on Google and found a recent video creating an integration, I realised that I have never seen the "Add Credentials" screen where it asks for the Oauth client id and client secret. 
<img width="399" alt="Screenshot 2024-11-10 at 01 12 24" src="https://github.com/user-attachments/assets/44a3bd3f-b2b3-4def-921b-704e91e4ed45">

I suspect this is why my integration is not working instead of configuring the wrong callback URL etc. (which I've left it at https://my.home-assistant.io/redirect/oauth) 

## Expected behavior

"Add Credentials" screen appearing at some point. 

## Actual behavior

No "Add Credentials" screen appearing. 

## Steps to reproduce

As described above.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by bevanting** [comment]
It worked! THANK YOU SO MUCH!!

**Comment by bevanting** [comment]
Oh, quick question: I have a Sleep Analyser Mat and it's added to Withings as that but in the integration, it's showing up as an Aura Sensor V2. 
Is that a bug?

**Comment by joostlek** [comment]
I think Withings has an issue in their API and didn't document this well. Do you maybe still have the box or can you find something like a revision ID on the box/device?

**Comment by bevanting** [comment]
I still have the box. I only bought the thing today so just tell me how / where I can find the information you need.

I've noticed that the settings to indicate if someone is in bed or out of bed are missing. Is that because it's identified as an Aura Sensor?

**Comment by bevanting** [comment]
![IMG_7710](https://github.com/user-attachments/assets/756b6cbf-b1d5-4926-9c63-4dd51a70f9d4)
![IMG_7711](https://github.com/user-attachments/assets/7aa20df2-9806-4599-8363-5b3622252678)
![IMG_7712](https://github.com/user-attachments/assets/bf3d9d8c-e74a-4c6b-85b8-0727be441c24)
![IMG_7713](https://github.com/user-attachments/assets/33214724-23b4-455e-952a-d78182928029)
Does these help?

Oh, so without Nabu Casa I can't get the in bed and out bed sensors? They are available on IFTTT though, I guess it's a "premium" function?

Thanks for all your help!

**Comment by bevanting** [comment]
From https://github.com/home-assistant/core/issues/68760 it seems people have gotten the in bed out bed sensors to work without Nabu Casa. Is that still the case? 
Is the use_webhook: true setting in configuration.yaml still valid?

**Comment by joostlek** [comment]
> Is the use_webhook: true setting in configuration.yaml still valid?

no

> Oh, so without Nabu Casa I can't get the in bed and out bed sensors?

> or exposed your instance to the internet the right way

:)

Thanks for the pictures, will have a check

**Comment by bevanting** [comment]
What do you mean “exposed to the internet the right way”? I am using cloudflare and have a proper domain name and can access HA when outside my house using https://mydomainname.com etc. 
I’ve signed up for the trial of Nabu Casa but it still doesn’t show those two settings which I need. 
I’ve returned it. Just going to build one using pressure mat and ESP32. :)

**Comment by joostlek** [comment]
If you exposed it on port 443 it should work after a restart

**Comment by bevanting** [comment]
Ahhh…that was easy enough. I did see somewhere 443 was mentioned but that was when the integration did not work at all. 
Afterwards the posts I saw were mainly talking about using web hooks and callback so I forgot all about 443. 
Oh well, I don’t have the product anymore. But I’ll keep that in mind if I decide to get it again. 
Many thanks for your help!

**Comment by joostlek** [comment]
No problem!
