### ISSUE TITLE
Unsupported value for <enum 'MeasurementType'>

### ISSUE THREAD

**Issue by KC-inDomus** [joostlek/python-withings#450]
# Problem/Motivation

Home Assistant 2024.11 logs says: `2024-11-18 11:53:05.254 WARNING (MainThread) [aiowithings] 227 is an unsupported value for <enum 'MeasurementType'>, please report this at https://github.com/joostlek/python-withings/issues`

Available to help troubleshooting, just ask.

**Comment by joostlek** [comment]
Thanks for reporting, this already has been reported in #434, so I will close this one
